<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>10.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <Target Name="CustomBeforeBuild" BeforeTargets="BeforeBuild">
        <Exec Command="g++ -std=c++17 -lstdc++ -shared -o libModel_calc.so -pedantic-errors -Wall -Werror -Wextra -fPIC CppLibrary/Model_calc.cc" IgnoreExitCode="false" />
    </Target>

    <ItemGroup>
        <Content Include="libModel_calc.so">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    
</Project>
